### ISSUE TITLE
Can it support setting the png raw data directly instead of fetch remotely.

### ISSUE THREAD

**Issue by jiazheng** [epistemex/pngtoy#9] opened 2017-01-16 15:50 UTC
Hi, I already have the raw data of a png file from server in the form of base64 string. So I can use your code to fetch the remote file. So can it support setting the png raw data directly? Thanks!

**Comment by epistemex** [comment] 2017-01-27 19:24
Thank you @jiazheng, it's being considered. As a workaround in the mean time you could simply prepend a data-uri header to the base64 string and you should be able to use that directly as a source for `fetch()` - this will also take care of converting it into binary format for you, in-memory:

    pngtoy.fetch("data:image/png;base64," + base64string);

If you have already decoded the base64 string you can use Object-URL instead (here assuming it has been decoded to an ArrayBuffer, or binary string):

    var url = (URL || webkitURL).createObjectURL([decodedBinaryData], {type: "image/png"});
    pngtoy.fetch(url);

The memory for it can be released using the `revokeObjectURL(url)` method.

**Comment by epistemex** [comment] 2017-01-27 19:38
Duplicate of issue #4

**Closed** 2017-01-27 19:38 UTC
Labels: feature request
